# Generated by Django 5.1.3 on 2024-11-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('image_path', models.FilePathField(blank=True, null=True, path='/path/to/store/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
