# Generated by Django 5.1.3 on 2024-11-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_codes', '0002_cachedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedImage',
        ),
    ]
