# Generated by Django 5.1.3 on 2024-11-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_codes', '0003_delete_cachedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsecodelist',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
